name: testing and deploying application in heroku

on:
  push:
   branches:
    - main
 
jobs:

  Testing_github_secrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions.checkout@v3
      - name: environment_test
        env:
          PORT: ${{ secrets.PORT }}
        run:  echo "${{ PORT }}"


  Testing_the_application:

    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Installing nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Starting a mongodb server
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: '5.0'

      - env:
          PORT: ${{ secrets.PORT }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        
      - run: npm ci
      - run: npm i jest --global
      - run: jest server/__tests__/friend.test.js
      - run: jest server/__tests__/group.test.js
      - run: jest server/__tests__/model.test.js
      - run: jest socket/__tests__/socket.test.js

      - name: Deploying to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: glacial-plains-37669
          heroku_email: deeppatra1999@gmail.com